### ISSUE TITLE
Problème sur render('fichier:bloc')

### ISSUE THREAD

**Issue by blr21560** [hugokernel/Hyla_Tpl#9]
Je n'arrive pas à mettre oeuvre une fonctionnalité où par la fonction render on appelle directement le fichier et le bloc (render('fichier:bloc')
Voici le code

```
    $tpl = new \Hyla_Tpl('template');
    $tpl->render('5-6.tpl:b2')  
```

le contenu du fichier 5-6.tpl

b1b2b3

Le message d'erreur indique que le le bloc b2 n'est pas trouvé.
Le fichier template n'est pas apparemment  lu.

**Comment by hugokernel** [comment]
Tu dois importer le fichier avant :

$tpl = new Hyla_Tpl('.');
$tpl->importFile('5-6.tpl');
echo $tpl->render('5-6.tpl:b2');
